<a href="https://colab.research.google.com/github/JManuelRG/sarscov2IPN/blob/main/Librer%C3%ADas/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Librería para trabajar con vectores y matrices

Explicación grabada:
https://youtu.be/QcEzAGZAqcs

## Vector: Arreglo unidimensional de datos

[1,2,3,4,5,6]

["A","B","C","D"]

# Listas

In [ ]:
# Lista
lista=[0,1,2,3,4,5]
lista

[0, 1, 2, 3, 4, 5]

In [ ]:
lista2=['A','C','T','G']
lista2

['A', 'C', 'T', 'G']

In [ ]:
# Son indexables
lista[3]

3

In [ ]:
lista2[2]

'T'

In [ ]:
lista2[0]='C'
lista2

['C', 'C', 'T', 'G']

In [ ]:
# Operaciones
3*lista

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [ ]:
# obtener el triple de cada elemento
for i in lista:
  lista[i]=3*lista[i]

lista

[0, 3, 6, 9, 12, 15]

# Tuplas

In [ ]:
# Tupla (tuple) Son inmutables
tupla = (0,1,2,3,4,5,6)
tupla

(0, 1, 2, 3, 4, 5, 6)

In [ ]:
tupla2=('A','C','T','G')
tupla2

('A', 'C', 'T', 'G')

In [ ]:
# Son indexables
tupla[1]

1

In [ ]:
for i in tupla:
  print(f"El elemento con índice {i} de la tupla es: {tupla[i]}")

El elemento con índice 0 de la tupla es: 0
El elemento con índice 1 de la tupla es: 1
El elemento con índice 2 de la tupla es: 2
El elemento con índice 3 de la tupla es: 3
El elemento con índice 4 de la tupla es: 4
El elemento con índice 5 de la tupla es: 5
El elemento con índice 6 de la tupla es: 6


In [ ]:
for i in range(0,len(tupla2)):
  print(f"El elemento con índice {i} de la tupla es: {tupla2[i]}")

El elemento con índice 0 de la tupla es: A
El elemento con índice 1 de la tupla es: C
El elemento con índice 2 de la tupla es: T
El elemento con índice 3 de la tupla es: G


In [ ]:
# Las Tuplas no son mutables
tupla
tupla[0]=99

TypeError: ignored

# Librería Numpy
Librería creada para trabajar con arreglos de datos,
vectores y matrices principalmente.

Página oficial:

https://numpy.org/

Tutoriales:

https://www.w3schools.com/python/numpy/numpy_intro.asp

In [ ]:
import numpy as np

In [ ]:
# Creación de un vector
vector1 = np.array([0,1,2,3,4,5,6,7])
print(vector1)

[0 1 2 3 4 5 6 7]


In [ ]:
#Indexación
vector1[2]

2

In [ ]:
#Operaciones:
3*vector1

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [ ]:
vector1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [ ]:
vector1[0]=100
vector1

array([100,   1,   2,   3,   4,   5,   6,   7])

# Matrices: 
## Arreglos bidimensionales de datos
Matriz 1
\begin{equation}
\begin{matrix}
a & b\\
c & d
\end{matrix}
\end{equation}


Matriz 2
\begin{equation}
\begin{matrix}
1 & 2\\
3 & 4
\end{matrix}
\end{equation}

In [ ]:
# Matrices
matriz1= np.array([['a','b'],
                   ['c','d']])
matriz1

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [ ]:
# Matrices
matriz2= np.array([['1','2'],
                   ['3','4']])
matriz2

array([['1', '2'],
       ['3', '4']], dtype='<U1')

In [ ]:
# Indexación
matriz2[0][1]


'2'

In [ ]:
for fila in range(0,2):
  for columna in range(0,2):
    print(f"El elemento de la fila {fila}, columna {columna} de la matriz1 es: {matriz2[fila][columna]}")

El elemento de la fila 0, columna 0 de la matriz1 es: 1
El elemento de la fila 0, columna 1 de la matriz1 es: 2
El elemento de la fila 1, columna 0 de la matriz1 es: 3
El elemento de la fila 1, columna 1 de la matriz1 es: 4


In [ ]:
matriz2

array([['1', '2'],
       ['3', '4']], dtype='<U1')

In [ ]:
# Operaciones con vectores
vector1

array([100,   1,   2,   3,   4,   5,   6,   7])

In [ ]:
len(vector1)

8

In [ ]:
vector2=np.linspace(0,10,8)
vector2

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [ ]:
vector1+vector2

array([100.        ,   2.42857143,   4.85714286,   7.28571429,
         9.71428571,  12.14285714,  14.57142857,  17.        ])

In [ ]:
# Operación append
lista.append(18)

lista

[0, 3, 6, 9, 12, 15, 18, 18]

In [ ]:
vector1

array([100,   1,   2,   3,   4,   5,   6,   7])

# Append para listas



In [ ]:
genoma1 = ['A','C','C','T','G']
genoma1

['A', 'C', 'C', 'T', 'G']

In [ ]:
3*genoma1

['A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G']

In [ ]:
genoma1.append(3*genoma1)

In [ ]:
genoma1

['A',
 'C',
 'C',
 'T',
 'G',
 ['A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G']]

# Slicing: Corte de elementos del vector

Método para aislar de manera directa fracciones del vector:

# vector[indice inicial:indice final]

In [ ]:
genoma3=np.array(['A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G','A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G','A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G'])

In [ ]:
genoma3

array(['A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C',
       'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A',
       'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T',
       'G', 'A', 'C', 'C', 'T', 'G'], dtype='<U1')

In [ ]:
len(genoma3)

45

In [ ]:
genoma3[0]

'A'

In [ ]:
#Desde el índice 10 al 32
genoma3[10:32]

array(['A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C',
       'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C'], dtype='<U1')

In [ ]:
# Desde el elemento 4 hasta el final del vector
genoma3[4:]

array(['G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C',
       'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G',
       'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C',
       'T', 'G'], dtype='<U1')

In [ ]:
# Desde el inicio del vector hasta el elemento 5
genoma3[:5]

array(['A', 'C', 'C', 'T', 'G'], dtype='<U1')

In [ ]:
# Corte con índice negativo
genoma3

array(['A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C',
       'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A',
       'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T', 'G', 'A', 'C', 'C', 'T',
       'G', 'A', 'C', 'C', 'T', 'G'], dtype='<U1')

In [ ]:
# El último elemento tiene un índice de -1
genoma3[-1]

'G'

In [ ]:
genoma3[-2]

'T'

In [ ]:
np.append(genoma3[-5:-1],genoma3[len(genoma3)-1])

array(['A', 'C', 'C', 'T', 'G'], dtype='<U1')

In [ ]:
genoma3[len(genoma3)-1]

'G'